.github/workflows/ci.yml, package.json, website/guide/components/inline-popover.md, website/guide/marks/bold.md, website/guide/marks/code.md, website/guide/marks/italic.md, website/guide/marks/link.md, website/guide/marks/strike.md, website/guide/marks/underline.md, website/guide/nodes/heading.md, website/guide/nodes/list.md
- fix build ci
- add ClientOnly
=> chore: fix the website build warning 

.github/workflows/ci.yml, playground/examples/lit-dom/editor.ts, playground/examples/lit-dom/language-selector.ts, playground/examples/react-code-block/language-selector.tsx, playground/examples/vue-code-block/language-selector.vue, playground/examples/vue-full/language-selector.vue, playground/uno.config.ts
Closes https://github.com/ocavue/prosekit/issues/293
=> fix(playground): show the language select in Firefox

website/guide/extensions.md, website/guide/integrations/react.md, website/guide/integrations/svelte.md, website/guide/integrations/vue.md, website/guide/marks/italic.md, website/guide/nodes/list.md, website/index.md
=> fix(website): Small corrections

.changeset/nine-pillows-relate.md, packages/extensions/src/link/index.ts, website/guide/marks/link.md
Simple command to remove link mark of a node.
=> feat(link): add `removeLink` command

.changeset/slimy-knives-count.md, packages/web/src/components/inline-popover/inline-popover/props.ts, packages/web/src/components/tooltip/tooltip-content/props.ts, packages/web/src/components/tooltip/tooltip-content/state.ts, packages/web/src/components/tooltip/tooltip-trigger/props.ts, playground/examples/react-code-block/toggle.tsx, playground/examples/react-heading/toggle.tsx, playground/examples/react-inline-menu/toggle.tsx, playground/examples/react-keymap/toggle.tsx, playground/examples/react-list/toggle.tsx, playground/examples/react-readonly/toggle.tsx, playground/examples/react-toolbar/toggle.tsx, playground/examples/vue-bold/toggle.vue, playground/examples/vue-code-block/toggle.vue, playground/examples/vue-code/toggle.vue, playground/examples/vue-full/toggle.vue, playground/examples/vue-heading/toggle.vue, playground/examples/vue-inline-menu/toggle.vue, playground/examples/vue-italic/toggle.vue, playground/examples/vue-keymap/toggle.vue, playground/examples/vue-list/toggle.vue, playground/examples/vue-readonly/toggle.vue, playground/examples/vue-strike/toggle.vue, playground/examples/vue-text-align/toggle.vue, playground/examples/vue-text-color/toggle.vue, playground/examples/vue-toolbar/toggle.vue, playground/examples/vue-underline/toggle.vue
=> fix(web): fix popover overflow

playground/src/layouts/base-layout.astro
https://github.com/ocavue/prosekit/assets/24715727/8552b9f4-c5b1-46b8-9199-e8655f927238
=> docs: set example max height

packages/core/src/facets/facet-node.test.ts, packages/core/src/facets/facet.test.ts
This pr introduces unit tests for `Facet` and `FacetNode`.
Not only guarantees the correctness of the code, but also helps to understand the code.
=> test: add unit test for facet

packages/web/package.json, playground/examples/react-code-block/button.tsx, playground/examples/react-heading/button.tsx, playground/examples/react-inline-menu/button.tsx, playground/examples/react-keymap/button.tsx, playground/examples/react-list/button.tsx, playground/examples/react-readonly/button.tsx, playground/examples/react-search/button.tsx, playground/examples/react-toolbar/button.tsx, playground/examples/vue-bold/button.vue, playground/examples/vue-code-block/button.vue, playground/examples/vue-code/button.vue, playground/examples/vue-full/button.vue, playground/examples/vue-heading/button.vue, playground/examples/vue-inline-menu/button.vue, playground/examples/vue-italic/button.vue, playground/examples/vue-keymap/button.vue, playground/examples/vue-list/button.vue, playground/examples/vue-readonly/button.vue, playground/examples/vue-strike/button.vue, playground/examples/vue-text-align/button.vue, playground/examples/vue-text-color/button.vue, playground/examples/vue-toolbar/button.vue, playground/examples/vue-underline/button.vue, pnpm-lock.yaml
https://github.com/prosekit/prosekit/assets/24715727/d4bea5da-9716-46a8-8c76-1ae556f11509
https://github.com/prosekit/prosekit/assets/24715727/a3a16d8c-dfc8-48dc-b5fd-d2aea86b9a28
=> docs: fix tooltip stacking order

.changeset/five-trees-joke.md, packages/vue/package.json, packages/vue/src/hooks/use-extension.spec.ts, packages/vue/src/injection/editor-context.ts, pnpm-lock.yaml
Closes https://github.com/prosekit/prosekit/issues/587
=> fix(vue): suppress context warning

packages/core/src/editor/union.ts, packages/core/src/editor/with-priority.ts, website/guide/extensions.md
Improve the docs for Extensions. Check the rendered preview page here: https://ocavue-docs-union--prosekit.netlify.app/guide/extensions
=> docs: explain union and withPriority

.changeset/wild-camels-do.md, packages/web/src/components/inline-popover/inline-popover/props.ts, packages/web/src/components/inline-popover/inline-popover/state.ts, packages/web/src/hooks/use-keymap.ts, playground/tests/inline-menu.test.ts
https://github.com/prosekit/prosekit/assets/24715727/abb51977-8987-44f0-a946-1a3cd49782c9
=> feat(web): press Escape to dismiss inline popovers

playground/example.meta.ts, playground/example.meta.yaml, playground/examples/svelte-change-tracking/editor-diff.svelte, playground/examples/svelte-change-tracking/editor-main.svelte, playground/examples/svelte-change-tracking/editor.svelte, playground/src/pages/[example].astro, playground/src/pages/index.astro, website/example-code-blocks/change-tracking/editor-diff.md, website/example-code-blocks/change-tracking/editor-main.md, website/example-code-blocks/change-tracking/editor.md, website/examples/change-tracking.md
https://github.com/prosekit/prosekit/assets/87414827/b67a17a3-da83-415c-9c41-5f1dace49284
=> docs: add svelte-change-tracking

packages/extensions/src/code-block/shiki-parser.ts
=> fix(code-block): delay shiki import

.changeset/soft-books-hammer.md, packages/web/src/components/table-handle/table-handle-root/state.ts
https://github.com/user-attachments/assets/6162a68c-ad38-4cd5-a0fc-e121d3a544c0
Closes https://github.com/prosekit/prosekit/issues/799
=> feat(table-handle): hide table handles when selecting text

.changeset/sharp-chicken-swim.md, packages/themes/dist/prosekit-themes.gen.js, packages/themes/src/classes.ts, playground/examples/react/table/table-handle.tsx, playground/examples/vue/table/table-handle.vue
=> docs: show keyboard shortcut in the table menu

packages/core/src/utils/parse.ts, packages/dev/src/gen-website-pages.ts, website/src/components/ui/landing/features-section.astro, website/src/content/docs/getting-started/introduction.mdx, website/src/content/docs/getting-started/saving-and-loading.mdx
Closes https://github.com/prosekit/prosekit/pull/831
=> docs: add conversion utilities

.changeset/giant-papayas-juggle.md, .changeset/pink-donuts-tease.md, packages/basic/src/typography.css, packages/web/src/components/block-handle/block-handle-popover/pointer-move.ts
Closes https://github.com/prosekit/prosekit/issues/940
=> fix(block-handle): show block handle outside of tables

packages/themes/src/classes.ts, website/src/components/ui/landing/editor-showcase.astro, website/src/examples/react/heading/editor.tsx, website/src/examples/solid/heading/editor.tsx, website/src/examples/svelte/heading/editor.svelte, website/src/examples/vue/heading/editor.vue, website/src/stories/container.astro, website/tests/heading.test.ts
=> docs: ensure editor demos have correct color

packages/typedoc-plugin/src/theme/context/partials/member.declarationBody.ts
=> docs: remove extra type declaration

packages/core/src/utils/type-assertion.ts, packages/typedoc-plugin/src/markdown-theme-context.ts, packages/typedoc-plugin/src/theme/context/partials/member.container.ts, packages/typedoc-plugin/src/theme/context/partials/member.declarationTitle.ts, packages/typedoc-plugin/src/theme/context/partials/member.signature.ts, packages/typedoc-plugin/src/theme/context/partials/member.signatureBody.ts, packages/typedoc-plugin/src/theme/context/partials/member.signatureTitle.ts
=> docs: refactor generate docs for functions
